# Generated by Django 4.1.7 on 2023-03-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='is_healthy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='toy',
            name='dogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
        ),
    ]
