# Generated by Django 4.1.7 on 2023-03-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_is_healthy_alter_toy_dogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='dogs',
        ),
        migrations.AddField(
            model_name='toy',
            name='dog',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='dogs.dog'),
        ),
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField()),
                ('adoption_fee', models.IntegerField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='dogs.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='dogs_m2m',
            field=models.ManyToManyField(through='dogs.DogOwner', to='dogs.dog'),
        ),
    ]
