# Generated by Django 4.1.7 on 2023-03-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_remove_toy_dogs_toy_dog_dogowner_owner_dogs_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogowner',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='dogs.dog'),
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.owner'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='dogs.dog'),
        ),
    ]
