# Generated by Django 4.1.7 on 2023-03-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dogowner_dog_alter_dogowner_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogowner',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='dogs.dog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.owner'),
            preserve_default=False,
        ),
    ]
