# Generated by Django 4.1.7 on 2023-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_alter_dogowner_dog_alter_dogowner_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='descriptions',
            field=models.CharField(default='Default Description', max_length=10000),
        ),
    ]
