# Generated by Django 4.1.7 on 2023-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
