# Generated by Django 4.1.7 on 2023-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
