# Generated by Django 4.1.7 on 2023-04-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
