# Generated by Django 4.1.7 on 2023-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0016_userprofile_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code_expires_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
