# Generated by Django 4.1.7 on 2023-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0017_alter_userprofile_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
