# Generated by Django 4.1.7 on 2023-05-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0020_alter_toy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogowner',
            name='user',
        ),
    ]
