# Generated by Django 4.1.7 on 2023-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0023_alter_toy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='mark',
            field=models.CharField(default='mark', max_length=50),
        ),
    ]
