# Generated by Django 4.1.7 on 2023-05-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0024_dog_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='mark',
        ),
    ]
