# Generated by Django 4.1.7 on 2023-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0026_alter_userprofile_country_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=150),
        ),
    ]
