# Generated by Django 4.1.7 on 2023-05-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0027_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='dogowner',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='user',
            new_name='users',
        ),
    ]
