# Generated by Django 4.1.7 on 2023-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0028_rename_user_dog_users_rename_user_dogowner_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=10000),
        ),
    ]
